services:
  database:
    image: mysql:latest
    container_name: mysql-iw
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: iw
      MYSQL_PASSWORD: iw
      MYSQL_DATABASE: project_backlog
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - infra

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-iw
    ports:
      - "8090:80"
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: iw
      PMA_PASSWORD: iw
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - database
    networks:
      - infra

networks:
  infra:

volumes:
  mysql-data:
